---
- name: Iptables_rules
  hosts: web_server
  become: yes
  tasks:
    - name: Allow Http traffic on port number 80
      iptables:
        chain: INPUT
        protocol: tcp
        destination_port: 80
        jump: ACCEPT

    - name: Allow Https traffic on port number 443
      iptables:
        chain: INPUT
        protocol: tcp
        destination_port: 443
        jump: ACCEPT
